config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  resources :artists, only: [:index, :show] do
    collection do
      get "filter/:filter" => "artists_filter#index", as: :filter
    end
  end
  resources :albums, only: [:index, :show] do
    collection do
      get "filter/:filter" => "albums_filter#index", as: :filter
    end
  end
  resources :tracks, only: [:index, :show] do
    collection do
      get "filter/:filter" => "tracks_filter#index", as: :filter
    end
    member do
      get "stream" => "stream_tracks#show", as: :stream
      get "add_to_playlist" => "playlist_tracks#show", as: :add_to_playlist
    end
  end
  
  get "radio" => "radio#index"

  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_flash_messages.html.haml
.absolute.top-0.right-px
  - if flash[:alert]
    .alert.p-2.bg-amber-300.text-amber-800.flex.justify-between.items-center.m-1
      .flex.items-center
        .text-3xl.me-2
          -# = render IconComponent.new(name: :exclamation_triangle)
        .me-2
          = flash[:alert]
      .cursor-pointer(data-action="click->alerts#dismiss")
        = render IconComponent.new(name: :close, size: 2)
  - if flash[:notice]
    .alert.p-2.bg-lime-300.text-lime-800.flex.justify-between.items-center.m-1
      .flex.items-center
        .text-3xl.me-2
          -# = render IconComponent.new(name: :smiley_face)
        .me-2 
          = flash[:notice]
      .cursor-pointer(data-action="click->alerts#dismiss")
        = render IconComponent.new(name: :close, size: 2)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Bard
      = yield :meta_title
    %meta(name="viewport" content="width=device-width, initial-scale=1")
    %meta(name="turbo-prefetch" content="false")
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
    = yield :head

    %body.bg-gray-800.text-gray-300
      #counts(data-artist="#{artist_count}" data-album="#{album_count}" data-track="#{track_count}")
      #bard-player
      
    -# %body.bg-gray-800.text-gray-300(data-controller="alerts")
      -# .flex.flex-row
      -#   .w-64.bg-gray-600.text-white(style="height: calc(100vh)")
      -#     .flex.flex-col
      -#       .flex.flex-row.w-full.justify-center.pt-8
      -#         = link_to root_path, "data-turbo-frame" => "content" do
      -#           .text-4xl.uppercase.text-gray-400.font-bold
      -#             Bard
            
      -#       .p-8
      -#         .text-lg.uppercase.text-gray-500 menu

      -#       = link_to artists_path, "data-turbo-frame" => "content", class: "ps-8 pe-8 pt-2 pb-2" do
      -#         .flex.flex-row.justify-between.items-center
      -#           %div Artists
      -#           .rounded-lg.shadow-sm.bg-gray-700.text-xs.p-1.font-thin
      -#             = artist_count

      -#       = link_to albums_path, "data-turbo-frame" => "content", class: "ps-8 pe-8 pt-2 pb-2" do
      -#         .flex.flex-row.justify-between.items-center
      -#           %div Albums
      -#           .rounded-lg.shadow-sm.bg-gray-700.text-xs.p-1.font-thin
      -#             = album_count

      -#       = link_to tracks_path, "data-turbo-frame" => "content", class: "ps-8 pe-8 pt-2 pb-2" do
      -#         .flex.flex-row.justify-between.items-center
      -#           %div Tracks
      -#           .rounded-lg.shadow-sm.bg-gray-700.text-xs.p-1.font-thin
      -#             = track_count

      -#       = link_to radio_path, "data-turbo-frame" => "content", class: "ps-8 pe-8 pt-2 pb-2" do
      -#         .flex.flex-row.justify-between.items-center
      -#           %div Radio
      -#           = render IconComponent.new(name: :radio, size: 3)
      -#   .w-full.overflow-auto(style="height: calc(100vh);")
      -#     = turbo_frame_tag "content" do
      -#       = yield

      -# %turbo-frame#player

    -#   .sticky.bottom-0.w-full.bg-gray-700.hidden(data-controller="player playlist track" data-player-target="main")
    -#     .flex.flex-col
    -#       .border-t.border-gray-500.hidden.flex.flex-row.justify-end.p-2(data-playlist-target="playlist" style="max-height: 350px")
    -#         .flex.flex-col
    -#           .pb-2.font-bold.text-3xl Playlist
    -#           .overflow-scroll(data-playlist-target="items")

    -#       %progress.w-full.bg-gray-700.cursor-pointer(data-player-target="progressbar" data-action="click->player#seek")
    -#       .flex.flex-row.p-3.pt-6.pb-6.justify-between.items-center
    -#         .flex.flex-row.items-center
    -#           .cursor-pointer(data-action="click->player#pause" data-player-target="pauseButton")
    -#             = render IconComponent.new(name: :pause, size: 4)
    -#           .hidden.cursor-pointer(data-action="click->player#play" data-player-target="playButton")
    -#             = render IconComponent.new(name: :play, size: 4)
    -#           .flex.flex-row.font-thin.ms-4
    -#             %span(data-track-target="elapsed") 00:00
    -#             .ms-1.me-1(data-track-target="durationDash") &mdash;
    -#             %span(data-track-target="duration") 00:00
    -#         .flex.flex-row
    -#           .bardplayer--cover-image(data-track-target="coverImage")
    -#             %img.rounded-lg(width="48px" height="48px" data-track-target="coverImageElement")
    -#           .bardplayer--cover-icon(data-track-target="coverIcon")
    -#             = render IconComponent.new(name: :album, size: 6)
    -#           .ms-4.flex.flex-col
    -#             .font-bold.text-md(data-track-target="title")
    -#               TITLE
    -#             .font-thin.text-sm
    -#               = link_to "empty", "data-turbo-frame" => "content", "data-track-target" => "artist" do
    -#                 ARTIST
    -#               &mdash;
    -#               = link_to "empty", "data-turbo-frame" => "content", "data-track-target" => "album" do
    -#                 ALBUM
    -#         %div
    -#           .flex.flex-row.items-center.hidden(data-playlist-target="buttons")
    -#             .me-2.font-thin(data-playlist-target="size")
    -#             .cursor-pointer(data-action="click->playlist#show" data-playlist-target="showButtons")
    -#               = render IconComponent.new(name: :chevron_up, size: 4)
    -#             .hidden.cursor-pointer(data-action="click->playlist#hide" data-playlist-target="hideButtons")
    -#               = render IconComponent.new(name: :chevron_down, size: 4)

    -# = render "/layouts/flash_messages"